version: "3.7"

services:

  mysql:
    image: mysql:5.6.35
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: pass
    healthcheck:
      test: mysqladmin ping -ppass
    ports:
      - 3306:3306

  gremlin:
    build: gremlin-server
    restart: on-failure
    ports:
      - 8182:8182
